version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8007:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8007

  frontend:
    build:
      context: ./frontend
    ports:
      - "3007:3000"
    volumes:
      - ./frontend:/app
    command: npm start
